version: '3.8'
services:
  postgres_application: # https://hub.docker.com/_/postgres
      container_name: postgres_application
      image: 'postgres:14.5-alpine'
      environment:
        POSTGRES_DB: image_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "postgres"
      ports:
        - "5433:5432"
      restart: on-failure
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - postgres:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - application_network
volumes:
  postgres:
networks:
  application_network: