camunda:
  client:
    mode: oidc
    tenant-ids:
      - <default>
    auth:
      oidc-type: keycloak
      issuer: keycloack:8080/auth/realms/camunda-platform
    zeebe:
      enabled: true
      gateway-url: zeebe:26500
      base-url: zeebe:8080
      prefer-rest-over-grpc: false
      audience: zeebe-api
    operate:
      enabled: true
      base-url: operate:8080
      audience: operate-api
    tasklist:
      enabled: true
      base-url: tasklist:8080
      audience: tasklist-api
    optimize:
      enabled: true
      base-url: optimize:8090
      audience: optimize-api
    identity:
      enabled: true
      base-url: identity:8084
      audience: identity-api
